### ISSUE TITLE
A look at Momocs

### ISSUE THREAD

**Issue by hzt314** [smarsland/pots#16]
I used data provided in simulating pots to check what Momocs can do with our project. The preliminary result is in momocs.pdf.

**Comment by dante3861** [comment]
[momocs.docx](https://github.com/smarsland/pots/files/4046728/momocs.docx)

**Comment by hzt314** [comment]
[momocs.pdf](https://github.com/smarsland/pots/files/4046776/momocs.pdf)

**Comment by dante3861** [comment]
Sorry I have no idea how to use this editing thing in github, plz check the attached pdf, thanks.

**Comment by Armand1** [comment]
Han --- that's great.  We need to Skype and we need to think how to use Mocmocs to make a good test.

**Comment by hzt314** [comment]
>Han --- that's great.  We need to Skype and we need to think how to use Mocmocs to make a good test. 

@Armand1 ok sir, I’m going to deal with my visa tomorrow and will be free since 1pm, please pick any time you want.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Armand1** [comment]
A useful discussion by Norman Mcleod on  [elliptical fourier transforms](https://www.palass.org/sites/default/files/media/palaeomath_101/article_25/article_25.pdf)
